apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kubeweb-ip
  labels:
    app: kube
spec:
  backend:
    serviceName: kubeweb-backend
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubeweb-backend
  labels:
    app: kube
spec:
  type: NodePort
  selector:
    app: kube
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
